# Generated by Django 6.0.4 on 2026-04-23 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('is_home', models.BooleanField(default=True)),
                ('our_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AtBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('batting_order_position', models.IntegerField(default=1)),
                ('result', models.CharField(blank=True, choices=[('', 'In Progress'), ('1B', 'Single'), ('2B', 'Double'), ('3B', 'Triple'), ('HR', 'Home Run'), ('BB', 'Walk'), ('HBP', 'Hit by Pitch'), ('K', 'Strikeout'), ('KL', 'Strikeout Looking'), ('GO', 'Ground Out'), ('FO', 'Fly Out'), ('LO', 'Line Out'), ('SAC', 'Sacrifice'), ('FC', "Fielder's Choice"), ('E', 'Error')], default='', max_length=4)),
                ('rbi', models.IntegerField(default=0)),
                ('runs_scored', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_bats', to='core.game')),
            ],
            options={
                'ordering': ['inning', 'batting_order_position'],
            },
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_number', models.IntegerField()),
                ('pitch_type', models.CharField(choices=[('FB', 'Fastball'), ('CB', 'Curveball'), ('SL', 'Slider'), ('CH', 'Changeup'), ('CT', 'Cutter'), ('SI', 'Sinker'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('result', models.CharField(choices=[('BALL', 'Ball'), ('STRIKE_S', 'Strike Swinging'), ('STRIKE_L', 'Strike Looking'), ('FOUL', 'Foul Ball'), ('IN_PLAY', 'In Play')], max_length=10)),
                ('velocity', models.IntegerField(blank=True, null=True)),
                ('balls_before', models.IntegerField(default=0)),
                ('strikes_before', models.IntegerField(default=0)),
                ('at_bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='core.atbat')),
            ],
            options={
                'ordering': ['pitch_number'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jersey_number', models.IntegerField(unique=True)),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['jersey_number'],
            },
        ),
        migrations.AddField(
            model_name='atbat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_bats', to='core.player'),
        ),
        migrations.CreateModel(
            name='LineupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_order', models.IntegerField()),
                ('position', models.CharField(max_length=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'ordering': ['batting_order'],
                'unique_together': {('game', 'batting_order')},
            },
        ),
    ]
